stages:
- preparation
- build
- release
- deploy

variables:

job_prepare:
  stage: preparation
  script:
  - echo "Project name -> '$CI_PROJECT_NAME'"
  - echo "Branch name -> '$CI_COMMIT_BRANCH'"
  - echo "Commit_id -> '$CI_COMMIT_SHA'"
  - echo "Coder -> $CI_COMMIT_AUTHOR"
  - echo "Description -> $CI_COMMIT_MESSAGE"
  rules:
  - if: '$CI_COMMIT_BRANCH == "staging"'

job_build_staging:
  stage: build
  script:
  - tbebuild
  # Run this job in a branch where a Dockerfile exists
  rules:
  - if: '$CI_COMMIT_BRANCH == "staging"'

job_release_staging:
  stage: release
  script:
  - tberelease
  rules:
  - if: '$CI_COMMIT_BRANCH == "staging"'



job_deploy_staging:
  stage: deploy
  script:
  - thelmsetinit staging
  - thelmupgrade staging
  rules:
  - if: '$CI_COMMIT_BRANCH == "staging"'

job_tag_release_production:
  stage: build
  script:
  - tbebuild
  - tdockertag $CI_COMMIT_TAG
  - tdockertagpush $CI_COMMIT_TAG
  # Run this job in a branch where a Dockerfile exists
  only:
  - tags

job_deploy_production:
  stage: deploy
  script:
  - thelmsetinitprod production $CI_COMMIT_TAG
  - thelmupgrade production
  only:
  - tags