version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "{APP_PORT-3014}:{APP_PORT-3014}"
    volumes:
      - ./app:/app
    environment:
      - APP_HOST=${APP_HOST-localhost}
      - APP_PORT=${APP_PORT-3014}
      - DB_TRANSACTION_DSN=${DB_TRANSACTION_DSN}
    networks:
      - mynetwork

networks:
  mynetwork:
    external: true
